site_name: An Economy of Eloquence
site_author: Nicholas Cornia
repo_url: https://github.com/NicholasCorniaOrpheus/an_economy_of_eloquence
nav:
  - Home: index.md
  - Wat is this game about?: about.md
  - Collaborative Research: collaborative_research.md
  - Core Rules: core_rules.md

plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css

#extra_javascript:
  #- assets/javascripts/extra.js

theme:
  name: material
  custom_dir: overrides
  #logo: assets/images/faam-logo-gold.png
  #favicon: assets/images/favicon.ico
  language: en
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      abstract: fontawesome/solid/book
      note: fontawesome/solid/note-sticky
      quote: fontawesome/solid/quote-left

  font:
      text: Sofia Sans
  palette:
    # Palette toggle for light mode
    #- scheme: default
      #primary: custom
      #default: custom
      #footer: custom
      #accent: custom
      #toggle:
        #icon: material/weather-night
        #name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      default: custom
      footer: custom
      accent: custom
      #toggle:
        #icon: material/weather-sunny
        #name: Switch to light mode        

  features:
    #- navigation.instant
    #- navigation.instant.prefetch
    #- navigation.instant.progress
    - search.share
    #- navigation.footer
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.top
    #- toc.follow
    #- toc

copyright: Copyright &copy; 2025 Orpheus Instituut, Resounding Libraries

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NicholasCorniaOrpheus
      name: GitHub repository
  social:
    - icon: material/music-note
      link: https://orpheusinstituut.be/
      name: Orpheus Instituut

markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - admonition
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
